### ISSUE TITLE
Nem lehet iskolát választani. (Linux)

### ISSUE THREAD

**Issue by FBSANAKONDA** [refilc/naplo#44]
Kali Linuxot használok (Igen tudom skid vagyok), szóval lényegében debian. Leszedtem a fluttert, klónoltam a repository-t, elindítottam a fix-pub.sh-t, ott kaptam egy kis errort: 

 ```
$ bash fix-pub.sh 
Resolving dependencies... (3.6s)
Note: material_color_utilities is pinned to version 0.5.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because filcnaplo depends on flutter_localizations from sdk which depends on material_color_utilities 0.5.0, material_color_utilities 0.5.0 is required.
So, because filcnaplo depends on material_color_utilities ^0.2.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on material_color_utilities: flutter pub add material_color_utilities:^0.5.0

```

de ezt megoldottam flutter pub add material_color_utilities:^0.5.0 -el, majd visszamentem a /naplo-ba és újra lefuttattam a bub-fix.sh-t ezúttal sikeresen. Elindítottam a naplót /naplo/filcnaplo-ban, De nem lehet iskolát választani. Rá kattintok, de nem tölti be az intézményhez, így nem tudok bejelentkezni. Az indításnál látható error:

```
$ flutter run                                    
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(filcnaplo:207267): Gdk-CRITICAL **: 21:26:47.519: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: [BackgroundFetch] ERROR: MissingPluginException(No implementation found for method configure on channel com.transistorsoft/flutter_background_fetch/methods)
flutter: [BackgroundFetch registerHeadlessTask] ‼️ MissingPluginException(No implementation found for method registerHeadlessTask on channel com.transistorsoft/flutter_background_fetch/methods)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.transistorsoft/flutter_background_fetch/methods)


══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
com.transistorsoft/flutter_background_fetch/events:
MissingPluginException(No implementation found for method listen on channel
com.transistorsoft/flutter_background_fetch/events)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════

Syncing files to device Linux...                                 1 624ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at: http://127.0.0.1:34453/3lsml79OEt4=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:34453/3lsml79OEt4=/
flutter: {user_agent: hu.ekreta.tanulo/$0/$1/$2}
```

https://github.com/refilc/naplo/assets/103428287/f9037853-d0cd-42be-b360-7f09a1812ee8

Nem értek a flutterhez, de e szerint egy plugin hiányzik, bár nem tudom, hogy az okozhatja-e ezt. Előre is köszönom, hogy ha utána néztek a problémámnak.

**Comment by kimaah** [comment]
`flutter channel stable` aztan `flutter upgrade`, es ha jo a flutter verzio es futtatod megint a fix-pub.sh-t, elvileg minden is mukodni fog (mi jelenleg 3.10.6-os flutter-t hasznalunk)

**Comment by FBSANAKONDA** [comment]
Így sem működik, ugyanazt az errort kapom, intézményt választani nem tudok. Visszamegyek 3.10.6-os fluterre és megpróbálom ott.

**Comment by FBSANAKONDA** [comment]
Flutter 3.10.6-al sem működik. Ugyanaz a probléma.

**Comment by kimaah** [comment]
koszonjuk flutter, de amugy ez olyan dolog hogy csak te tudod megoldani mert mindenkinek mashogy mukodik xd

**Comment by FBSANAKONDA** [comment]
Megpróbáltam, nem működött. Még vissza is mentem flutter 3.10.6-ra, ott is ugyanaz volt a probléma.

**Comment by FBSANAKONDA** [comment]
Próbálkozom, majd valahogy megoldom. Ha meg nem, akkor meg ez van, nem olyan tragédia.

**Comment by PearooXD** [comment]
Azóta ez megoldódott?

**Comment by JeromeSchmied** [comment]
Nekem is hasonló hiba van, Arch-on, fluttert flutter.dev-ről szereztem, de alapból nem értek hozzá, csak ki akartam próbálni laptopon a refilcet.
```
$ flutter --version
Flutter 3.13.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6c4930c4ac (7 days ago) • 2023-10-18 10:57:55 -0500
Engine • revision 767d8c75e8
Tools • Dart 3.1.4 • DevTools 2.25.0
``` 
Iskolát nem tudok választani.
`sh fix-pub.sh` hibátlanul futott ilyen kimenettel:
```
$ sh fix-pub.sh 
Deleting build...                                                   32ms
Deleting .dart_tool...                                               7ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting ephemeral...                                                3ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
  collection 1.17.2 (1.18.0 available)
  confetti 0.6.0 (0.7.0 available)
  connectivity_plus 4.0.2 (5.0.1 available)
  coverage 1.6.4 (1.7.1 available)
  dropdown_button2 1.9.4 (2.3.9 available)
  file_picker 5.5.0 (6.0.0 available)
  fl_chart 0.45.1 (0.64.0 available)
  flutter_expandable_fab 1.8.1 (2.0.0 available)
  flutter_linkify 5.0.2 (6.0.0 available)
  flutter_lints 2.0.3 (3.0.0 available)
  flutter_local_notifications 14.1.4 (16.1.0 available)
  flutter_svg 1.1.6 (2.0.8 available)
  go_router 10.2.0 (12.0.0 available)
  home_widget 0.1.6 (0.3.0 available)
  http 0.13.6 (1.1.0 available)
  image_picker 0.8.9 (1.0.4 available)
  image_picker_for_web 2.2.0 (3.0.1 available)
  linkify 4.1.0 (5.0.0 available)
  lints 2.1.1 (3.0.0 available)
  lottie 1.4.3 (2.7.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  permission_handler 10.4.5 (11.0.1 available)
  permission_handler_android 10.3.6 (12.0.1 available)
  permission_handler_platform_interface 3.12.0 (4.0.1 available)
  petitparser 5.4.0 (6.0.1 available)
  provider 5.0.0 (6.0.5 available)
  rive 0.9.1 (0.12.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.3 (1.24.9 available)
  test_api 0.6.0 (0.6.1 available)
  test_core 0.5.3 (0.5.9 available)
  uuid 3.0.7 (4.1.0 available)
  vm_service 11.10.0 (13.0.0 available)
  web 0.1.4-beta (0.3.0 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
Deleting .dart_tool...                                               2ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
  collection 1.17.2 (1.18.0 available)
  confetti 0.6.0 (0.7.0 available)
  connectivity_plus 4.0.2 (5.0.1 available)
  coverage 1.6.4 (1.7.1 available)
  dropdown_button2 1.9.4 (2.3.9 available)
  file_picker 5.5.0 (6.0.0 available)
  fl_chart 0.45.1 (0.64.0 available)
  flutter_expandable_fab 1.8.1 (2.0.0 available)
  flutter_linkify 5.0.2 (6.0.0 available)
  flutter_lints 1.0.4 (3.0.0 available)
  flutter_local_notifications 14.1.4 (16.1.0 available)
  flutter_svg 1.1.6 (2.0.8 available)
  go_router 10.2.0 (12.0.0 available)
  home_widget 0.1.6 (0.3.0 available)
  http 0.13.6 (1.1.0 available)
  image_picker 0.8.9 (1.0.4 available)
  image_picker_for_web 2.2.0 (3.0.1 available)
  linkify 4.1.0 (5.0.0 available)
  lints 1.0.1 (3.0.0 available)
  lottie 1.4.3 (2.7.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  permission_handler 10.4.5 (11.0.1 available)
  permission_handler_android 10.3.6 (12.0.1 available)
  permission_handler_platform_interface 3.12.0 (4.0.1 available)
  petitparser 5.4.0 (6.0.1 available)
  provider 5.0.0 (6.0.5 available)
  rive 0.9.1 (0.12.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.3 (1.24.9 available)
  test_api 0.6.0 (0.6.1 available)
  test_core 0.5.3 (0.5.9 available)
  uuid 3.0.7 (4.1.0 available)
  vm_service 11.10.0 (13.0.0 available)
  web 0.1.4-beta (0.3.0 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
Deleting .dart_tool...                                               2ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
  collection 1.17.2 (1.18.0 available)
  confetti 0.6.0 (0.7.0 available)
  connectivity_plus 4.0.2 (5.0.1 available)
  coverage 1.6.4 (1.7.1 available)
  dropdown_button2 1.9.4 (2.3.9 available)
  file_picker 5.5.0 (6.0.0 available)
  fl_chart 0.45.1 (0.64.0 available)
  flutter_expandable_fab 1.8.1 (2.0.0 available)
  flutter_linkify 5.0.2 (6.0.0 available)
  flutter_lints 1.0.4 (3.0.0 available)
  flutter_local_notifications 14.1.4 (16.1.0 available)
  flutter_svg 1.1.6 (2.0.8 available)
  go_router 10.2.0 (12.0.0 available)
  home_widget 0.1.6 (0.3.0 available)
  http 0.13.6 (1.1.0 available)
  image_picker 0.8.9 (1.0.4 available)
  image_picker_for_web 2.2.0 (3.0.1 available)
  linkify 4.1.0 (5.0.0 available)
  lints 1.0.1 (3.0.0 available)
  lottie 1.4.3 (2.7.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  permission_handler 10.4.5 (11.0.1 available)
  permission_handler_android 10.3.6 (12.0.1 available)
  permission_handler_platform_interface 3.12.0 (4.0.1 available)
  petitparser 5.4.0 (6.0.1 available)
  provider 5.0.0 (6.0.5 available)
  rive 0.9.1 (0.12.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.3 (1.24.9 available)
  test_api 0.6.0 (0.6.1 available)
  test_core 0.5.3 (0.5.9 available)
  uuid 3.0.7 (4.1.0 available)
  vm_service 11.10.0 (13.0.0 available)
  web 0.1.4-beta (0.3.0 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
Deleting .dart_tool...                                               2ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
  collection 1.17.2 (1.18.0 available)
  confetti 0.6.0 (0.7.0 available)
  connectivity_plus 4.0.2 (5.0.1 available)
  coverage 1.6.4 (1.7.1 available)
  dropdown_button2 1.9.4 (2.3.9 available)
  file_picker 5.5.0 (6.0.0 available)
  fl_chart 0.45.1 (0.64.0 available)
  flutter_expandable_fab 1.8.1 (2.0.0 available)
  flutter_linkify 5.0.2 (6.0.0 available)
  flutter_lints 1.0.4 (3.0.0 available)
  flutter_local_notifications 14.1.4 (16.1.0 available)
  flutter_svg 1.1.6 (2.0.8 available)
  go_router 10.2.0 (12.0.0 available)
  home_widget 0.1.6 (0.3.0 available)
  http 0.13.6 (1.1.0 available)
  image_picker 0.8.9 (1.0.4 available)
  image_picker_for_web 2.2.0 (3.0.1 available)
  linkify 4.1.0 (5.0.0 available)
  lints 1.0.1 (3.0.0 available)
  lottie 1.4.3 (2.7.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  permission_handler 10.4.5 (11.0.1 available)
  permission_handler_android 10.3.6 (12.0.1 available)
  permission_handler_platform_interface 3.12.0 (4.0.1 available)
  petitparser 5.4.0 (6.0.1 available)
  provider 5.0.0 (6.0.5 available)
  rive 0.9.1 (0.12.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.3 (1.24.9 available)
  test_api 0.6.0 (0.6.1 available)
  test_core 0.5.3 (0.5.9 available)
  uuid 3.0.7 (4.1.0 available)
  vm_service 11.10.0 (13.0.0 available)
  web 0.1.4-beta (0.3.0 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
Deleting .dart_tool...                                               3ms
Deleting .flutter-plugins-dependencies...   
``` 
De futtatásnál ezt írja ki
```
$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(filcnaplo:161762): Gdk-CRITICAL **: 21:27:46.308: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: [BackgroundFetch] ERROR: MissingPluginException(No implementation found for method configure on channel com.transistorsoft/flutter_background_fetch/methods)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.transistorsoft/flutter_background_fetch/methods)


══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
com.transistorsoft/flutter_background_fetch/events:
MissingPluginException(No implementation found for method listen on channel
com.transistorsoft/flutter_background_fetch/events)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:652:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════

flutter: [BackgroundFetch registerHeadlessTask] ‼️ MissingPluginException(No implementation found for method registerHeadlessTask on channel com.transistorsoft/flutter_background_fetch/methods)
Syncing files to device Linux...                                   442ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at: http://127.0.0.1:33225/PuZZEGjkJk0=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:33225/PuZZEGjkJk0=/
flutter: {user_agent: hu.ekreta.student/$0/$1/$2}
``` 
ami így néz ki:
![image](https://github.com/refilc/naplo/assets/118479592/a4623506-bfda-4115-95b3-22750c9c1e5b)

**Comment by ReinerRego** [comment]
Alapból nem fog futni a background fetch gépen, de nem mükszik a desktopos verzió.
Valamelyik update elcseszte az os felismerést, így csak a mobile ui van jelen.
Az is fog megjelenni mindenhol, gépet beleértve
De ha lesz időm megcsinálom, úgyis már régóta tervben van
